/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#410002",
        "error": "#ba1a1a",
        "inverse-on-surface": "#eff1f3",
        "primary-fixed-dim": "#b4c5ff",
        "on-background": "#191c1e",
        "secondary-container": "#7cf994",
        "on-surface": "#191c1e",
        "secondary": "#006e2d",
        "surface-variant": "#e0e3e5",
        "on-primary-container": "#eeefff",
        "tertiary": "#ae0010",
        "surface-container-low": "#f2f4f6",
        "inverse-primary": "#b4c5ff",
        "on-surface-variant": "#434655",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "tertiary-container": "#d52022",
        "on-tertiary": "#ffffff",
        "secondary-fixed-dim": "#62df7d",
        "surface-container": "#eceef0",
        "on-primary-fixed": "#00174b",
        "surface-dim": "#d8dadc",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#007230",
        "on-primary": "#ffffff",
        "surface-container-high": "#e6e8ea",
        "surface-tint": "#0053db",
        "primary-fixed": "#dbe1ff",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#93000b",
        "surface": "#f7f9fb",
        "tertiary-fixed-dim": "#ffb4ab",
        "surface-bright": "#f7f9fb",
        "on-secondary-fixed": "#002109",
        "surface-container-highest": "#e0e3e5",
        "on-primary-fixed-variant": "#003ea8",
        "primary": "#004ac6",
        "secondary-fixed": "#7ffc97",
        "on-tertiary-container": "#ffecea",
        "tertiary-fixed": "#ffdad6",
        "background": "#f7f9fb",
        "outline": "#737686",
        "inverse-surface": "#2d3133",
        "on-secondary-fixed-variant": "#005320",
        "primary-container": "#2563eb",
        "outline-variant": "#c3c6d7",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        base: "4px",
        "container-padding": "16px",
        "touch-target-min": "44px",
        gutter: "12px",
        "margin-mobile": "16px",
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-lg": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "price-lg": ["18px", { lineHeight: "24px", fontWeight: "700" }],
        display: ["30px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
}
